### ISSUE TITLE
Timers are not cancelled when receiving ack for data sent

### ISSUE THREAD

**Issue by amjaingzb** [Juniper/warp17#36]
There is a bug where in the timers are not cancelled, when the acknowledgement arrives for the data segment, which causes the timer queues to keep growing (and also re-transmissions).
Setup : establish 1 connection with a test duration of say 2 seconds, in a back to back setup with port 0 as part of client profile and port 1 as part of server profile.  
There after issue 
warp17> show timer statistics
Port 0 TCP Timer statistics:
  RTO Timer Set       :                  356
  RTO Timer Cancelled :                   1
  RTO Timer Fired     :                  354

Port 1 TCP Timer statistics:
  RTO Timer Set       :                  356
  RTO Timer Cancelled :                   1
  RTO Timer Fired     :                  354

I have made a corresponding fix for the same,
refer : https://github.com/amjaingzb/warp17/commit/ed5f2810939fa0686759dff0c1a2b96612272313
src/tpg_tcp_sm.c
@@ -1262,6 +1262,8 @@ static int tsm_SF_estab(tcp_control_block_t *tcb, tcpEvent_t event,
                 SEG_LE(seg_ack, tcb->tcb_snd.nxt)) {
                 /* Will update tcb_snd.una inside! */
                 tsm_cleanup_retrans_queu(tcb, seg_ack);
+                /* Cancel the retransmission timer */
+                tcp_timer_rto_cancel(&tcb->tcb_l4);
             }
 
             /*

**Comment by dceara** [comment]
@amjaingzb Thanks for the issue report!

About your fix, I'm afraid in certain scenarios you will cancel the retransmission timer too early. For example, if the TCP ACK we received acks only part of the data we have on the retransmission lists then the RTO timer should stay on the run queue because there's more data that needs to be acked.

I think a better place to cancel the RTO timer is inside `tsm_cleanup_retrans_queu` if all the data on the retransmission list was acked (`if (retrans->tr_data_mbufs == NULL)`). Like that we should cover all cases.

Please feel free to open a pull request and I'll merge the fix once available.

Thanks,
Dumitru

**Comment by amjaingzb** [comment]
Thanks Dumitru,
I tried with the change you propose and its working fine (although I have just done basic sanity). 
I have done the fix. https://github.com/Juniper/warp17/compare/dev/common...amjaingzb:patch-2

regards,
Amit Jain

**Comment by dceara** [comment]
Thanks Amit. I just ran the complete unit test suite and I see no issues. I opened a pull request on your behalf and I'll merge the fix as soon as possible.

Regards,
Dumitru

**Comment by dceara** [comment]
Fixed through commit https://github.com/Juniper/warp17/commit/c7c0aa63a9a8d37e536c98aa402d791e37b444da. Will be available in v1.5.
