### ISSUE TITLE
Need support for Latency measurement on WARP17

### ISSUE THREAD

**Issue by mrakesha** [Juniper/warp17#43]
Hi Dumitru,

We need latency stats support on WARP17, it can help us often identifying the problem when application/network performance is slow and low.  Thanks in advance.

Thanks,
Rakesh mishra

**Comment by davvore33** [comment]
Hi Rakesha Mishra,
I’ll take care about this since now
———————————————————————————
Matteo Triggiani,
Sustaining Engineering Team

mtriggiani@juniper.net<mailto:mtriggiani@juniper.net>

On 18 Aug 2017, at 2:29 PM, mrakesha <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dumitru,

We need latency stats support on WARP17, it can help us often identifying the problem when application/network performance is slow and low. Thanks in advance.

Thanks,
Rakesh mishra

**Comment by dceara** [comment]
Fixed by @davvore33 with commit https://github.com/Juniper/warp17/commit/cc78a4324da1e61d4573af27f38c52051a10a6bc.

Will be available in v1.5.
