### ISSUE TITLE
ARP packets/bytes sent are not getting added into port Link TX counters.

### ISSUE THREAD

**Issue by chandrasheker** [Juniper/warp17#50]
ARP packets/bytes received are getting added into port link RX counters, but ARP packets/bytes sent are not getting added into port link TX counters.

**Comment by chandrasheker** [comment]
Only server side Link RX counters are getting incremented for ARP packet/byte received, on client side both TX and RX are not getting incremented for ARP packets/bytes.

**Comment by chandrasheker** [comment]
In test_start_cb function we are trying to clear port stats after sending ARP packets. Please update the function so that clearing of stats will be done before sending ARP packets.

**Comment by dceara** [comment]
@chandrasheker Thanks for the bug report. I'll take care of it soon.

**Comment by chandrasheker** [comment]
Hi @dceara now link TX counters are getting updated properly(after changing code to reset stats before ARP packets send) but receive link counters on client are not getting updated properly. I was going through the code to find out where we are doing wrong, but I'm unable to find out whats wrong on client side. If you can find and share any pointer to fix this thing will be very help full for me.

Thanks,
Chandrasheker M.

**Comment by chandrasheker** [comment]
I'm trying to run both client and server on same instance of warp17.. at start of the test cases we are trying to clear link stats because of very minimal delay between start of server and client ports client stats are getting cleared and we are unable to Rx bytes of client properly. I feel clearing of stats should be done manually by user or after the end of test case we can clear :) Hope this analysis will help you in fixing the issue.

**Comment by dceara** [comment]
Hi @chandrasheker,

The reason why we don't clear stats automatically when `tests stop port <x>` is executed is because we don't want to lose the test case statistics. A user might want to stop all traffic and then collect the test case related statistics. We already have the `clear stats port <x>` CLI that can be run at any time to clear non-test-case-related stats manually.

I will remove the port stats clearing code from `test_start_cb`:
```
/* Clear port stats. */
rte_eth_stats_reset(start_msg->tssm_eth_port);
rte_eth_xstats_reset(start_msg->tssm_eth_port);
```

Then only test case related stats will be cleared when `tests start port <x>` is run. If you wish to clear all statistics (including link/ETH/ARP/IP/TCP/UDP) before running a test you will have to execute:

```
clear stats port <X>
tests start port <X>
tests stop port <X>
```

At this point you can collect all stats you need:
- test case related stats (e.g., http stats, sessions up, sessions failed)
- per port stats (e.g., link, ARP, TCP)

Will this approach work for your use case?

**Comment by dceara** [comment]
Fixed by commit https://github.com/Juniper/warp17/commit/1982d73ea3ca5e4ffbbb1c608978c6c06f0a4b1d.
