### ISSUE TITLE
README.md missing important information

### ISSUE THREAD

**Issue by krisk0** [Juniper/warp17#84]
## Short story
How much memory is spent per TCP connection? per packet? How many CPU cores should be used? I suggest this should be clearly stated in README.

## Long story

My boss wants to know how many TCP connections can be kept up/set up by our software ... say software router. So I am making a simple virtual stand with two copies of warp17 and our router:
```
warp17 client <-> our software <-> warp17 server
```
Need many ports in sport/dport setting, need lots of memory (-m --tcb-pool-sz). Count of connections is count of client ports by count of server ports; size of memory for TCP is set by parameter --tcb-pool-sz. And how do I set tcb-pool-sz without knowing size of memory spent for one TCP connection (`sizeof(tcp_control_block_t)` if I guessed right)?

Getting sizeof(tcp_control_block_t) was not very easy for me, because warp17 uses ancient versions of DPDK and protobuf (and thus we build it in a container), and because just including `tpg_tcp.h` did not work. I got 280 bytes, is that right?

How many CPU cores do I need? Two cores are used for user interface, are they also used for packet processing or just stay idle when there is no UI? There is one core per port queue, will it be better if I add more cores than two plus count of port queues?

I suggest that important information about packet/protocol processing such as sizes of data structures, CPU core usage be published.

**Comment by dceara** [comment]
@krisk0 Warp17 runs on LTS versions of DPDK and we plan to keep it like that. We do use an older version of protobuf because of the limited functionalities of the protobuf-c libraries wrt RPC. We plan to upgrade it.

Fwiw `sizeof(tcp_control_block_t)` __on my test machine__ (which may be quite different than what you're running) in warp17 v1.8 with DPDK 16.11 LTS is:
```
(gdb) p sizeof(tcp_control_block_t)
$1 = 312
```
However, this doesn't say enough to answer the question "how much memory is used by X sessions". That is because sessions are allocated from mempools and, for efficiency reasons and by default DPDK mempools don't allocate objects contiguously. Instead each object will be cache aligned and moreover the objects will be spread such that all memory channels (configurable through the `-n` switch) are used. So you should not expect that a tcb pool size of 2K would use up 2K * 312 bytes.

I understand the need for a memory estimate so we'll update the README with information about memory usage in various cases __on our reference platform__. However, the big disclaimer is that all these numbers can differ on other platforms.

To answer the CPU core related question: yes, two cores are used for the UI (actually CLI and test management). To save a core you could use the `--lcores` dpdk command line arg to bundle those two lcores on a single physical core (see [dpdk doc section 3.3.1](https://doc.dpdk.org/guides-17.11/prog_guide/env_abstraction_layer.html)). Wrt. number of queues, you shouldn't add more cores than the number of queues supported by the hardware NIC.

**Comment by krisk0** [comment]
Thank you for nearly complete answer.

When you update documentation, please mension the upper limit on `--tcb-pool-sz` parameter. IMHO there are at least 2 bounds: 
```
x <= 2**32 - 2**10
1024 * x  / active cores count <= limit of mem_create_local_pool(,,,312,)
```
I am currently trying to figure out the right-hand side of the second bound.

And will warp17 client/server run better (keep/generate more TCP sessions) if count of cores is larger than 2+queues count?
