### ISSUE TITLE
Warp17 client never closes established connections

### ISSUE THREAD

**Issue by krisk0** [Juniper/warp17#85]
Short story: when I put down router and warp17 server, warp17 client reports huge number of established connections.

Long story follows.

Configure client as follows:
```
add tests client tcp port 0 test-case-id 0 src 1.1.1.9 1.1.1.9 sport 1 3100 dest 2.2.2.9 2.2.2.9 dport 1 5200

set tests criteria port 0 test-case-id 0 run-time 100
set tests timeouts port 0 test-case-id 0 uptime infinite

set tests client raw port 0 test-case-id 0 data-req-plen 1 data-resp-plen 1

set tests tcp-options port 0 test-case-id 0 syn-retry 1
set tests tcp-options port 0 test-case-id 0 syn-ack-retry 1
set tests tcp-options port 0 test-case-id 0 data-retry 1
set tests tcp-options port 0 test-case-id 0 rto 50
set tests tcp-options port 0 test-case-id 0 fin-to 100
set tests tcp-options port 0 test-case-id 0 twait-to 50
set tests tcp-options port 0 test-case-id 0 orphan-to 100
set tests tcp-options port 0 test-case-id 0 twait-skip 1
```
Configure server as follows:
```
add tests l3_intf port 0 ip 2.2.2.9 mask 255.255.255.0
add tests l3_gw port 0 gw 2.2.2.8
add tests server tcp port 0 test-case-id 0 src 2.2.2.9 2.2.2.9 sport 1 5200
set tests server raw port 0 test-case-id 0 data-req-plen 1 data-resp-plen 1

<Same TCP options as above>
```
Run server and client as separate programs, with router in-between. Watch count of established connections
```
while 1:
 r0 = warp17_method_call(warp17_host, warp17_port, Warp17_Stub, 'GetTestStatus', TestCaseArg(tca_eth_port=0, tca_test_case_id=0))
 print r0.tsr_stats.gs_estab
 tiime.sleep(1)
```
Once some connections are established, put down router and server, so nothing can take a packet from, or send packet to warp17 client.

**Expected behavior**: count of connections goes down in less than a second. Reason: 1 control or data packet should be resend, then timeout should occur, total sum of timeouts is less than 1 second.

**Observed behavior**: count of connections remains unchanged for at least 20 seconds.

Warp17 version: 1.8. 

I am ready to supply more information if necessary, of course.

**Comment by davvore33** [comment]
hi @krisk0, I was able to replicate the issue, I'm looking into it right now, thanks for reporting

**Comment by davvore33** [comment]
hi @krisk0 
We find out that those sessions which stay in "ESTABLISHED" state on client side, are waiting for replies but have no pending retransmission timer as they already received ACKs for all their sends, we already planned to add a timer that will kill those sessions so you'll see this problem fixed in next releases

**Comment by davvore33** [comment]
hi @krisk0 
We find out that those sessions which stay in "ESTABLISHED" state on client side, are waiting for replies but have no pending retransmission timer as they already received ACKs for all their sends, we already planned to add a timer that will kill those sessions so you'll see this problem fixed in next releases

**Comment by davvore33** [comment]
hi @krisk0 
We find out that those sessions which stay in "ESTABLISHED" state on client side, are waiting for replies but have no pending retransmission timer as they already received ACKs for all their sends, we already planned to add a timer that will kill those sessions so you'll see this problem fixed in next releases

**Comment by krisk0** [comment]
In my test, client indefinitely sends 1-byte payloads. I am surprised that it stays connected after seeing no reply at all.

Waiting for fixed version of warp17. I hope to finally find out how many connections can get thru our software router.
