### ISSUE TITLE
DPDK 18.08 support with Warp 17-1.8

### ISSUE THREAD

**Issue by 0xROLANDIAN** [Juniper/warp17#96]
Hi I have a Warp17-1.8 and dpdk 18.08 (on Centos 7.0.1406). I tried to make Warp17 after installing protobuf dependencies as outlined in README.md
````
/opt/warp17-1.8/src/tpg_arp.c:422:5: error: ‘rte_eth_dev_count’ is deprecated (declared at /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:1398) [-Werror=deprecated-declarations]
     if (STATS_LOCAL_INIT(tpg_arp_statistics_t, "arp_stats", lcore_id) == NULL) {
     ^
cc1: all warnings being treated as errors
make[2]: *** [tpg_arp.o] Error 1
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/warp17-1.8'
````
It fails to compile, but reading around I see that versions of warp on support certain versions on dpdk, so if I want to use I will have to downgrade my version ?  I would like to avoid that as I have already pre-compliled dpdk applications developed on 18.08.

Any advice would be gratefully received.

Thanks!

**Comment by davvore33** [comment]
Hi @hyperhead ,
I'm sorry to inform you that Warp17 [`v1.8`](https://github.com/Juniper/warp17/tree/v1.8) (the latest stable) supports only dpdk since <=16.11, if you need to use greater version of dpdk you can use branch [`dev/common`](https://github.com/Juniper/warp17/tree/dev/common) which actually supports dpdk version 17.11.3

**Comment by 0xROLANDIAN** [comment]
Hi davvore33,   Ok thanks for update.
